package vars

var QEMU_SYSTEMS = []string{
	"qemu-system-aarch64",
	"qemu-system-mips",
	"qemu-system-s390x",
	"qemu-system-alpha",
	"qemu-system-mips64",
	"qemu-system-sh4",
	"qemu-system-arm",
	"qemu-system-mips64el",
	"qemu-system-sh4eb",
	"qemu-system-avr",
	"qemu-system-mipsel",
	"qemu-system-sparc",
	"qemu-system-hppa",
	"qemu-system-or1k",
	"qemu-system-sparc64",
	"qemu-system-i386",
	"qemu-system-ppc",
	"qemu-system-tricore",
	"qemu-system-loongarch64",
	"qemu-system-ppc64",
	"qemu-system-x86_64",
	"qemu-system-m68k",
	"qemu-system-riscv32",
	"qemu-system-xtensa",
	"qemu-system-microblaze",
	"qemu-system-riscv64",
	"qemu-system-xtensaeb",
	"qemu-system-microblazeel",
	"qemu-system-rx",
}

var QEMU_ACCEL = []string{
	"kvm",
	"hax",
	"whpx",
	"tcg",
	"hvf",
	"xen",
	"none",
}
